"""add usage_records

Revision ID: d8d98191e643
Revises: 0002
Create Date: 2026-04-10 14:55:06.793170
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8d98191e643'
down_revision: Union[str, None] = '0002'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usage_records',
    sa.Column('api_definition_id', sa.Uuid(), nullable=False, comment='FK → api_definitions'),
    sa.Column('api_key_id', sa.Uuid(), nullable=False, comment='FK → api_keys'),
    sa.Column('api_code', sa.String(length=128), nullable=False, comment='API code snapshot'),
    sa.Column('request_id', sa.Uuid(), nullable=False, comment='Unique request ID'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP status code'),
    sa.Column('latency_ms', sa.Integer(), nullable=False, comment='Processing time in milliseconds'),
    sa.Column('tokens_used', sa.Integer(), nullable=False, comment='AI tokens consumed'),
    sa.Column('request_ip', sa.String(length=64), nullable=True, comment='Client IP'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usage_records_api_code'), 'usage_records', ['api_code'], unique=False)
    op.create_index(op.f('ix_usage_records_api_definition_id'), 'usage_records', ['api_definition_id'], unique=False)
    op.create_index(op.f('ix_usage_records_api_key_id'), 'usage_records', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_usage_records_created_at'), 'usage_records', ['created_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_records_created_at'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_key_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_definition_id'), table_name='usage_records')
    op.drop_index(op.f('ix_usage_records_api_code'), table_name='usage_records')
    op.drop_table('usage_records')
    # ### end Alembic commands ###
