"""add prompt_versions

Revision ID: e2601813cfca
Revises: d8d98191e643
Create Date: 2026-04-12 12:56:26.638943
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'e2601813cfca'
down_revision: Union[str, None] = 'd8d98191e643'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_versions',
    sa.Column('api_definition_id', sa.Uuid(), nullable=False, comment='FK → api_definitions'),
    sa.Column('version', sa.Integer(), nullable=False, comment='Auto-incremented version number'),
    sa.Column('prompt_text', sa.Text(), nullable=False, comment='Full prompt content'),
    sa.Column('accuracy_score', sa.Float(), nullable=False, comment='Accuracy on evaluation set (0-1)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Currently active version'),
    sa.Column('parent_version_id', sa.Uuid(), nullable=True, comment='Parent version for iteration chain tracking'),
    sa.Column('optimization_metadata', sqlite.JSON(), nullable=True, comment='Optimization process metadata (diff, eval details)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_api_definition_id'), 'prompt_versions', ['api_definition_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prompt_versions_api_definition_id'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    # ### end Alembic commands ###
